# PROJETO

Tratamento e análise de dados com Pandas

1. Procurar um dataset (Conjunto de dados) interessante;
    - Kaggle;
    - UCI Datasets; 
    - IBGE;
    - Outras fontes de interesse. 
2. Descrever os dados (nulos, valores distintos, tipos de variáveis...);
3. Fazer o tratamento de qualidade dos dados (Remover nulos, remover valores constantes, ...)
4. Levantar 10 perguntas sobre o dataset e responder utilizado filtragens, agrupamentos e transformações no Pandas.

Entrega: 

- Repositório do github (Envie o link do repositório);
- Pelo menos 3 commits no github ;
- No repositório deve conter o dataset e o arquivo .ipynb;
- Entrega até o dia 03/10 no LMS;

In [51]:
import pandas as pd

bank = pd.read_csv("bank.csv", sep = ";")

bank.shape

(4521, 17)

In [52]:
bank.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [53]:
# quero ver a 10 ultimas linhas 
bank.tail(10)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
4511,46,blue-collar,married,secondary,no,668,yes,no,unknown,15,may,1263,2,-1,0,unknown,yes
4512,40,blue-collar,married,secondary,no,1100,yes,no,unknown,29,may,660,2,-1,0,unknown,no
4513,49,blue-collar,married,secondary,no,322,no,no,cellular,14,aug,356,2,-1,0,unknown,no
4514,38,blue-collar,married,secondary,no,1205,yes,no,cellular,20,apr,45,4,153,1,failure,no
4515,32,services,single,secondary,no,473,yes,no,cellular,7,jul,624,5,-1,0,unknown,no
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [54]:
#Quantos dados são nulos

bank.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [55]:
# Descrição das idades (age)
bank["age"].describe()

count    4521.000000
mean       41.170095
std        10.576211
min        19.000000
25%        33.000000
50%        39.000000
75%        49.000000
max        87.000000
Name: age, dtype: float64

In [56]:
# Descrição dos trabalhos (job)
bank["job"].describe()

count           4521
unique            12
top       management
freq             969
Name: job, dtype: object

In [57]:
# Descrição do estado civil (marital)
bank["marital"].describe()

count        4521
unique          3
top       married
freq         2797
Name: marital, dtype: object

In [58]:
# Descrição do nível escolar (education)
bank["education"].describe()

count          4521
unique            4
top       secondary
freq           2306
Name: education, dtype: object

In [59]:
# Descrição se possui operação de crédito (defaut)
bank["default"].describe()

count     4521
unique       2
top         no
freq      4445
Name: default, dtype: object

In [ ]:
# Este é o campo do salário médio anual (balance)
bank["balance"].describe()

count     4521.000000
mean      1422.657819
std       3009.638142
min      -3313.000000
25%         69.000000
50%        444.000000
75%       1480.000000
max      71188.000000
Name: balance, dtype: float64